#? Rules can be added here as most of the configuration are dynamic

# // █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# // ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hypr.land/Configuring/Window-Rules/

# hyprlang if HYPRLAND_V_0_53

# Fix file chooser dialogs opening off-screen
windowrule = float on, match:tag portal-dialogs
windowrule = center on, match:tag portal-dialogs

# Only add the Core applications here
windowrule = tag +hyde_floating_apps, match:class ^(blueman-manager|pavucontrol-qt|com\.gabm\.satty|vlc|kvantummanager|qt[56]ct|nwg-(look|displays)|org\.kde\.ark|org\.pulseaudio\.pavucontrol|blueman-manager|nm-(applet|connection-editor)|org\.kde\.polkit-kde-authentication-agent-1|console-dropdown)$

windowrule = tag +hyde_floating_apps, match:class ^(org\.kde\.dolphin)$, match:title ^(Progress Dialog — Dolphin|Copying — Dolphin)$

# common popups
windowrule = tag +hyde_common_popups, match:title ^(Choose Files|Save As|Confirm to replace files|File Operation Progress|Open|Authentication Required|Add Folder to Workspace|File Upload.*|Choose wallpaper.*|Library.*|.*dialog.*)$
windowrule = tag +hyde_common_popups, match:initial_title ^(Open File|Volume Control|Save As.*)$
windowrule = tag +hyde_common_popups, match:class ^(.*dialog.*|[Xx]dg-desktop-portal-gtk)$

windowrule = tag +hyde_portal_dialogs, match:class ^(org\.freedesktop\.impl\.portal\.desktop\.(hyprland|gtk)|[Xx]dg-desktop-portal-gtk)$

# Picture-in-Picture
windowrule = tag +picture-in-picture, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = tag +hyde_picture_in_picture, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = float on, match:tag hyde_picture_in_picture
windowrule = keep_aspect_ratio on, match:tag hyde_picture_in_picture
windowrule = move (monitor_w*0.73) (monitor_h*0.72), match:tag hyde_picture_in_picture
windowrule = size (monitor_w*0.25) (monitor_h*0.25), match:tag hyde_picture_in_picture
windowrule = pin on, match:tag hyde_picture_in_picture

windowrule = float on, match:tag hyde_floating_apps
windowrule = float on, center on, match:tag hyde_common_popups
windowrule = float on, center on, match:tag hyde_portal_dialogs

# // █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# // █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur on, match:namespace ^(rofi|notifications|swaync-(notification-window|control-center)|waybar|logout_dialog)$
layerrule = ignore_alpha 0, match:namespace ^(rofi|notifications|swaync-(notification-window|control-center)|logout_dialog|waybar|selection)$
layerrule = no_anim on, match:namespace selection

# hyprlang endif

# hyprlang if !HYPRLAND_V_0_53

source = $XDG_DATA_HOME/hyde/migration/hypr/0.52_windowrules.conf

# hyprlang endif
