# Rules can be added here as most of the configuration are dynamic

# // █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# // ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Sizes for floating popups
windowrulev2 = float, title:(Open File|Choose Files|Save As|Confirm to replace files|File Operation Progress)
windowrulev2 = size 85% 95%, title:(Open File|Choose Files|Save As|Confirm to replace files|File Operation Progress)
windowrulev2 = tag +common-popups, title:(Open File|Choose Files|Save As|Confirm to replace files|File Operation Progress)


# Only add the Core applications here
windowrulev2 = float, class:(com.gabm.satty)
windowrulev2 = float, class:(org.kde.dolphin), title:(Progress Dialog — Dolphin)
windowrulev2 = float, class:(org.kde.dolphin), title:(Copying — Dolphin)
windowrulev2 = float, title:(About Mozilla Firefox)
windowrulev2 = float, class:(firefox), title:(Picture-in-Picture)
windowrulev2 = float, class:(firefox), title:(Library)

windowrulev2 = float, initialTitle:(top)
windowrulev2 = float, initialTitle:(btop)
windowrulev2 = float, initialTitle:(htop)

windowrulev2 = float, class:(vlc)
windowrulev2 = float, class:(kvantummanager)
windowrulev2 = float, class:(qt5ct)
windowrulev2 = float, class:(qt6ct)
windowrulev2 = float, class:(nwg-look)
windowrulev2 = float, class:(nwg-displays)
windowrulev2 = float, class:(org.kde.ark)
windowrulev2 = float, class:(org.pulseaudio.pavucontrol)
windowrulev2 = float, class:(blueman-manager)
windowrulev2 = float, class:(nm-applet)
windowrulev2 = float, class:(nm-connection-editor)
windowrulev2 = float, class:(org.kde.polkit-kde-authentication-agent-1)
windowrulev2 = float, class:([Xx]dg-desktop-portal-gtk)


# // █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# // █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule2 = blur,rofi
layerrule2 = ignorezero,rofi
layerrule2 = blur,notifications
layerrule2 = ignorezero,notifications
layerrule2 = blur,swaync-notification-window
layerrule2 = ignorezero,swaync-notification-window
layerrule2 = blur,swaync-control-center
layerrule2 = ignorezero,swaync-control-center
layerrule2 = blur,logout_dialog
layerrule2 = ignorezero,logout_dialog
layerrule2 = blur,waybar
layerrule2 = ignorezero,waybar

