#!/usr/bin/env bash
# Generated by Source/locale/build.py; do not edit manually.
# shellcheck shell=bash disable=SC2034
declare -gA _T 2>/dev/null || declare -A _T 2>/dev/null || :
_T[$'Description']=$'说明'
_T[$'Initialization failed.']=$'初始化失败。'
_T[$'Keybind Hint']=$'快捷键提示'
_T[$'Keybind cache updated']=$'快捷键缓存已更新'
_T[$'Keybindings']=$'快捷键'
_T[$'Keybinds']=$'快捷键'
_T[$'Notifications']=$'通知'
_T[$'Repeat']=$'重复执行'
_T[$'[Enter] repeat; [ESC] exit']=$'[Enter] 重复；[ESC] 退出'
_T[$'click-left: Enable & Disable DND']=$'左键：启用/关闭免打扰'
_T[$'click-middle: clear history']=$'中键：清空历史记录'
_T[$'click-right: close all']=$'右键：关闭全部通知'
_T[$'rofi not detected. Displaying on terminal instead']=$'未检测到 rofi，改为在终端中显示'
_T[$'scroll-down: history pop']=$'向下滚动：弹出历史通知'
