[global]
    action      = "sync"
    description = "Choose a shell"
    include     = [ "../dots/zsh.toml", "../dots/fish.toml", "../dots/nushell.toml" ]
    owner       = "The HyDE Project"
    version     = "latest"
