
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hypr.land/Configuring/Monitors/

# Atari VCS 800 - 1080p @ 100Hz
monitor=HDMI-A-1,1920x1080@100,0x0,1
