# // █▀▀ ▄▀█ █▀▄▀█ █▀▀ █▀▄▀█ █▀█ █▀▄ █▀▀
# // █▄█ █▀█ █░▀░█ ██▄ █░▀░█ █▄█ █▄▀ ██▄

<<<<<<< HEAD
# Script from https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#toggle-animationsbluretc-hotkey
=======
# Script from https://wiki.hypr.land/Configuring/Uncommon-tips--tricks/#toggle-animationsbluretc-hotkey
>>>>>>> master

$WORKFLOW_ICON=  # this is an indicator that can be parsed by waybar or other status guis
$WORKFLOW_DESCRIPTION = Emphasis on performance and disabling compositors expensive features

decoration {
<<<<<<< HEAD
    shadow {        
=======
    shadow {
>>>>>>> master
        enabled = 0
    }
    blur {
        enabled = 0
        xray = 1
    }
<<<<<<< HEAD
    rounding = 0 
    active_opacity = 1 
    inactive_opacity = 1 
    fullscreen_opacity = 1 
=======
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1
>>>>>>> master
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
}

animations:enabled = 0

<<<<<<< HEAD
layerrule = noanim,waybar 
layerrule = noanim,swaync-notification-window 
layerrule = noanim,swww-daemon 
layerrule = noanim,rofi

windowrule = opaque,class:(.*) # ensure all windows are opaque 
=======
windowrule = opaque true,match:class (.*) # ensure all windows are opaque

layerrule {
name = workflows_gaming
blur = false
no_anim = true
match:namespace = ^(rofi|notifications|swaync-(notification-window|control-center)|logout_dialog|waybar|.*www-daemon)$
}
>>>>>>> master
