-- Auto-generated by DOORwayDE wallbash system — do not edit directly
-- Run 'doorwayde-shell themeselect' or a wallpaper change to regenerate

--------------------------------------------------------------------------------
-- Theme Identity
--------------------------------------------------------------------------------

local DOORWAYDE_THEME = "Catppuccin Mocha"
local GTK_THEME       = "Catppuccin-Mocha"
local COLOR_SCHEME    = "prefer-dark"
local ICON_THEME      = "Tela-circle-dracula"

--------------------------------------------------------------------------------
-- Cursor
--------------------------------------------------------------------------------

local CURSOR_THEME = "Bibata-Modern-Ice"
local CURSOR_SIZE  = 24

--------------------------------------------------------------------------------
-- Fonts
--------------------------------------------------------------------------------

local FONT                = "Cantarell"
local FONT_SIZE           = 10
local DOCUMENT_FONT       = "Cantarell"
local DOCUMENT_FONT_SIZE  = 10
local MONOSPACE_FONT      = "CaskaydiaCove Nerd Font Mono"
local MONOSPACE_FONT_SIZE = 9

--------------------------------------------------------------------------------
-- Misc
--------------------------------------------------------------------------------

local CODE_THEME  = "Wallbash"
local SDDM_THEME  = ""
