
# // ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# // █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█

<<<<<<< HEAD
# See https://wiki.hyprland.org/Configuring/Animations/
=======
# See https://wiki.hypr.land/Configuring/Animations/
>>>>>>> master
# credits: https://github.com/prasanthrangan/hyprdots

animations:enabled=false

