name: Warn Master Branch PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  warn-master-branch-pr:
    name: Warn about PR targeting master branch
    if: github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Add warning comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const issue_number = context.issue.number;
            
            // Check if we already commented on this PR
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number
            });
            
            const botComment = comments.data.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('⚠️ Warning: PR targeting master branch')
            );
            
            if (!botComment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: "⚠️ **Warning: PR targeting master branch detected!**\n\nThis pull request is attempting to merge changes into the `master` branch. This is typically not recommended because:\n\n1. **Protected workflow**: The master branch should usually be protected and only updated through specific processes\n2. **Stability concerns**: Direct merges to master can introduce instability to the main codebase\n3. **Best practices**: Changes should typically go through a development branch (like `dev` or `develop`) first\n\n**Recommended action:**\n- Consider changing the target branch to `dev` or `develop` instead\n- If this is a hotfix or emergency change, ensure it has been properly reviewed\n- Make sure all tests pass and the change has been thoroughly tested\n\nIf this PR targeting master is intentional and has been approved by maintainers, you can ignore this warning.\n\n---\n*This is an automated message. If you believe this warning is incorrect, please contact the maintainers.*"
              });
              console.log('Warning comment added to PR #' + issue_number);
            } else {
              console.log('Warning comment already exists for PR #' + issue_number);
            }
