name: Warn Master Branch PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  warn-master-branch-pr:
    name: Warn about PR from master branch
    if: github.event.pull_request.head.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Add warning comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const issue_number = context.issue.number;
            
            // Check if we already commented on this PR
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number
            });
            
            const botComment = comments.data.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('⚠️ Warning: PR from master branch')
            );
            
            if (!botComment) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: "⚠️ **Warning: PR from master branch detected!**\n\nThis pull request appears to be created from the `master` branch. This is typically not recommended because:\n\n1. **Development workflow**: Contributions should usually be made from feature branches or the `dev` branch\n2. **Merge conflicts**: Working directly on master can lead to merge conflicts and complications\n3. **Best practices**: It's safer to create a feature branch for your changes\n\n**Recommended action:**\n- Create a new branch from your current changes: `git checkout -b feature/your-feature-name`\n- Push the new branch and create a new PR from that branch instead\n\nIf this PR is intentional (e.g., hotfix or emergency change), you can ignore this warning.\n\n---\n*This is an automated message. If you believe this warning is incorrect, please contact the maintainers.*"
              });
              console.log('Warning comment added to PR #' + issue_number);
            } else {
              console.log('Warning comment already exists for PR #' + issue_number);
            }
